# docker-compose.yml
# Defines Docker services for local development and testing databases.

version: '3.8'

services:
  # ----------------------------------------------------
  # Development Database Service
  # Used for local development and manual testing.
  # ----------------------------------------------------
  db_dev:
    image: postgres:16-alpine # Using a lightweight PostgreSQL image
    container_name: fitflix_db_dev
    restart: always # Always restart the container if it stops
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    environment:
      POSTGRES_DB: fitflix_dev_db # Database name for development
      POSTGRES_USER: postgres      # Default user
      POSTGRES_PASSWORD: 12345     # Password (use a strong one in production!)
    volumes:
      # Persist data to a named volume to prevent data loss on container stop/remove
      - fitflix_dev_data:/var/lib/postgresql/data
    healthcheck: # Health check to ensure the database is ready
      test: ["CMD-SHELL", "pg_isready -U postgres -d fitflix_dev_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ----------------------------------------------------
  # Testing Database Service
  # Used exclusively for automated integration tests.
  # Runs on a different port to avoid conflicts with the dev DB.
  # ----------------------------------------------------
  db_test:
    image: postgres:16-alpine
    container_name: fitflix_db_test
    restart: always
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432
    environment:
      POSTGRES_DB: fitflix_test_db # Database name for testing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      # Persist data to a named volume for the test DB
      - fitflix_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fitflix_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  fitflix_dev_data: # Named volume for development data persistence
  fitflix_test_data: # Named volume for testing data persistence