name: Basic Status Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main # Or your development branch, e.g., 'main'
      - master # Or your production branch, e.g., 'master'
      - feature/** # If you want it to run on feature branches too

jobs:
  report_success:
    runs-on: ubuntu-latest
    steps:
      - name: Report success status
        run: echo "This is a dummy check that always succeeds."
      - name: Set status check result
        # This step is crucial for reporting a named status check
        run: |
          echo "Status check 'always-succeeds-check' has passed."
        env:
          # This is how you report a specific status check name back to GitHub
          # Make sure the name 'always-succeeds-check' is unique and descriptive
          STATUS_CHECK_NAME: always-succeeds-check
